import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { Printer, RotateCcw } from 'lucide-react';
import { api } from '../api/http.js';
import { PageHeader } from '../components/PageHeader.jsx';
import { currency, dateTime } from '../utils/format.js';
import { printReturnDocument } from '../utils/returnPrint.js';

export function PurchaseReturns() {
  const [filters, setFilters] = useState({ q: '', supplier: '', product: '', from: '', to: '' });
  const [purchases, setPurchases] = useState([]);
  const [purchase, setPurchase] = useState(null);
  const [quantities, setQuantities] = useState({});
  const [reason, setReason] = useState('');
  const [preview, setPreview] = useState(false);
  const [history, setHistory] = useState([]);
  const loadHistory = () => api.get('/returns/purchases').then((res) => setHistory(res.data.returns || []));
  useEffect(() => { loadHistory(); }, []);
  useEffect(() => { const timer = setTimeout(() => api.get('/returns/purchases/search', { params: filters, silent: true }).then((res) => setPurchases(res.data.purchases || [])).catch(() => {}), 250); return () => clearTimeout(timer); }, [filters]);

  async function open(id) { const { data } = await api.get(`/returns/purchases/source/${id}`); setPurchase(data.purchase); setQuantities({}); setPreview(false); }
  const selected = useMemo(() => (purchase?.items || []).map((item) => { const id = String(item.product?._id || item.product); const quantity = Number(quantities[id] || 0); const taxableAmount = quantity * Number(item.costPrice || 0); const gstAmount = taxableAmount * Number(item.gstRate || 0) / 100; return { ...item, id, quantity, returnAmount: taxableAmount + gstAmount }; }).filter((item) => item.quantity > 0), [purchase, quantities]);
  const total = selected.reduce((sum, item) => sum + item.returnAmount, 0);
  function fullReturn() { setQuantities(Object.fromEntries((purchase?.items || []).map((item) => [String(item.product?._id || item.product), Number(item.returnableQuantity || 0)]))); }
  async function complete() { if (!reason.trim()) return toast.error('Enter a return reason'); if (!selected.length) return toast.error('Select return items'); const { data } = await api.post('/returns/purchases', { purchaseId: purchase._id, reason, items: selected.map((item) => ({ productId: item.id, quantity: item.quantity })) }); toast.success(`Return ${data.purchaseReturn.returnNo} completed`); setReason(''); setPreview(false); await open(purchase._id); await loadHistory(); }

  return <div><PageHeader title="Purchase Return" description="Supplier returns with stock, GST, purchase value, and outstanding reconciliation." />
    <div className="panel p-4"><div className="grid gap-3 md:grid-cols-5"><input className="input" placeholder="Invoice number" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })}/><input className="input" placeholder="Supplier" value={filters.supplier} onChange={(e) => setFilters({ ...filters, supplier: e.target.value })}/><input className="input" placeholder="Product" value={filters.product} onChange={(e) => setFilters({ ...filters, product: e.target.value })}/><input className="input" type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })}/><input className="input" type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })}/></div><div className="mt-3 max-h-44 overflow-auto">{purchases.map((entry) => <button key={entry._id} onClick={() => open(entry._id)} className="flex w-full justify-between border-b p-2 text-left hover:bg-slate-50"><span><b>{entry.invoiceNumber || entry._id}</b> · {entry.supplier?.name || '-'}</span><span>{currency(entry.total)} · {dateTime(entry.purchaseDate)}</span></button>)}</div></div>
    {purchase && <div className="panel mt-5 p-5"><div className="flex justify-between"><div><h2 className="text-lg font-bold">Purchase {purchase.invoiceNumber}</h2><p className="text-sm text-slate-500">{purchase.supplier?.name || '-'} · {dateTime(purchase.purchaseDate)}</p></div><button className="btn-muted" onClick={fullReturn}><RotateCcw size={16}/>Full Return</button></div><div className="mt-4 overflow-x-auto"><table className="w-full"><thead><tr><th className="table-th">Product</th><th className="table-th">Purchased</th><th className="table-th">Returned</th><th className="table-th">Return Qty</th><th className="table-th">Cost</th><th className="table-th">GST</th><th className="table-th">Value</th></tr></thead><tbody>{purchase.items.map((item) => { const id = String(item.product?._id || item.product); const max = Number(item.returnableQuantity || 0); const qty = Number(quantities[id] || 0); const value = qty * Number(item.costPrice || 0) * (1 + Number(item.gstRate || 0) / 100); return <tr key={id}><td className="table-td"><b>{item.name || item.product?.name}</b><div className="text-xs">{item.product?.sku || ''}</div></td><td className="table-td">{item.quantity} {item.unit}</td><td className="table-td">{item.returnedQuantity || 0}</td><td className="table-td"><input className="input w-28" type="number" min="0" max={max} step="0.001" value={quantities[id] || ''} onChange={(e) => setQuantities({ ...quantities, [id]: Math.min(max, Math.max(0, Number(e.target.value))) })}/><small className="block">Max {max}</small></td><td className="table-td">{currency(item.costPrice)}</td><td className="table-td">{item.gstRate || 0}%</td><td className="table-td">{currency(value)}</td></tr>})}</tbody></table></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_auto]"><input className="input" placeholder="Return reason" value={reason} onChange={(e) => setReason(e.target.value)}/><strong className="self-center">Value: {currency(total)}</strong><button className="btn-primary" onClick={() => setPreview(true)}>Preview Return</button></div></div>}
    {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="panel w-full max-w-xl p-5"><h2 className="text-xl font-bold">Confirm Supplier Return</h2>{selected.map((item) => <p key={item.id} className="flex justify-between border-b py-2"><span>{item.name} · {item.quantity} {item.unit}</span><b>{currency(item.returnAmount)}</b></p>)}<p className="mt-3 text-right text-xl font-bold">Return Value {currency(total)}</p><div className="mt-4 flex justify-end gap-2"><button className="btn-muted" onClick={() => setPreview(false)}>Back</button><button className="btn-primary" onClick={complete}>Complete Return</button></div></div></div>}
    <div className="panel mt-5 p-5"><h2 className="font-bold">Purchase Return History</h2>{history.map((entry) => <div key={entry._id} className="mt-2 flex flex-wrap items-center justify-between gap-2 border-b py-2"><span><b>{entry.returnNo}</b> · {entry.originalInvoiceNo} · {entry.supplierName || '-'}</span><span>{currency(entry.returnAmount)} · {dateTime(entry.returnDate)}</span><span className="flex gap-1">{['72mm','80mm','A4'].map((width) => <button key={width} className="btn-muted py-1" onClick={() => printReturnDocument(entry, 'purchase', width)}><Printer size={14}/>{width}</button>)}</span></div>)}</div>
  </div>;
}
