import express from 'express';
import { authRoutes } from './authRoutes.js';
import { auditRoutes } from './auditRoutes.js';
import { accountingRoutes } from './accountingRoutes.js';
import { backupRoutes } from './backupRoutes.js';
import { billRoutes } from './billRoutes.js';
import { brandRoutes } from './brandRoutes.js';
import { holdBillRoutes } from './holdBillRoutes.js';
import { categoryRoutes } from './categoryRoutes.js';
import { customerRoutes } from './customerRoutes.js';
import { exportRoutes } from './exportRoutes.js';
import { expenseRoutes } from './expenseRoutes.js';
import { inventoryRoutes } from './inventoryRoutes.js';
import { productRoutes } from './productRoutes.js';
import { purchaseRoutes } from './purchaseRoutes.js';
import { purchaseOrderRoutes } from './purchaseOrderRoutes.js';
import { reportRoutes } from './reportRoutes.js';
import { returnRoutes } from './returnRoutes.js';
import { saleRoutes } from './saleRoutes.js';
import { settingsRoutes } from './settingsRoutes.js';
import { supplierRoutes } from './supplierRoutes.js';
import { taxRoutes } from './taxRoutes.js';
import { unitRoutes } from './unitRoutes.js';
import { userRoutes } from './userRoutes.js';
import { getDashboard } from '../controllers/dashboardController.js';
import { protect, requirePermission } from '../middleware/auth.js';

export const apiRoutes = express.Router();

apiRoutes.get('/health', (req, res) => res.json({ success: true, message: 'Server running' }));
apiRoutes.use('/auth', authRoutes);
apiRoutes.use('/accounting', protect, requirePermission('accounting'), accountingRoutes);
apiRoutes.get('/dashboard', protect, requirePermission('dashboard'), getDashboard);
apiRoutes.use('/users', protect, requirePermission('users'), userRoutes);
apiRoutes.use('/categories', protect, requirePermission('products'), categoryRoutes);
apiRoutes.use('/brands', protect, requirePermission('products'), brandRoutes);
apiRoutes.use('/taxes', protect, requirePermission('products'), taxRoutes);
apiRoutes.use('/products', protect, requirePermission('products'), productRoutes);
apiRoutes.use('/customers', protect, requirePermission('customers'), customerRoutes);
apiRoutes.use('/suppliers', protect, requirePermission('purchases'), supplierRoutes);
apiRoutes.use('/units', unitRoutes);
apiRoutes.use('/sales', protect, requirePermission('billing'), saleRoutes);
apiRoutes.use('/purchases', protect, requirePermission('purchases'), purchaseRoutes);
apiRoutes.use('/purchase-orders', protect, requirePermission('purchases'), purchaseOrderRoutes);
apiRoutes.use('/inventory', protect, requirePermission('inventory'), inventoryRoutes);
apiRoutes.use('/reports', protect, requirePermission('reports'), reportRoutes);
apiRoutes.use('/exports', exportRoutes);
apiRoutes.use('/expenses', protect, requirePermission('expenses'), expenseRoutes);
apiRoutes.use('/returns', returnRoutes);
apiRoutes.use('/settings', protect, requirePermission('settings'), settingsRoutes);
apiRoutes.use('/backup', protect, requirePermission('settings'), backupRoutes);
apiRoutes.use('/audit-logs', protect, requirePermission('settings'), auditRoutes);
apiRoutes.use('/bills', protect, requirePermission('billing'), billRoutes);
apiRoutes.use('/hold-bills', protect, requirePermission('billing'), holdBillRoutes);
